# Generated by Django 2.2.11 on 2020-03-19 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=40)),
                ('first_name', models.CharField(max_length=40)),
                ('middle_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=6)),
                ('nida_no', models.CharField(max_length=25)),
                ('phone_no', models.CharField(max_length=22)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('region', models.CharField(max_length=22)),
                ('approved_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('rank_level', models.IntegerField(default=0)),
                ('date_of_birth', models.DateField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='university',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=60)),
                ('university_location', models.CharField(max_length=60, null=True)),
                ('created_on', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='work_experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=60)),
                ('company_name', models.CharField(max_length=75)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_registration.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='university_agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('middle_name', models.CharField(default='', max_length=40)),
                ('Last_name', models.CharField(max_length=40)),
                ('staff_id', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('phone_no', models.CharField(max_length=22)),
                ('username', models.CharField(default='', max_length=40)),
                ('password', models.CharField(default='', max_length=40)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_registration.university')),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=75)),
                ('explaination', models.CharField(max_length=250, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_registration.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('Link', models.CharField(max_length=400)),
                ('role', models.CharField(max_length=50)),
                ('yeard', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_registration.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_name', models.CharField(max_length=50)),
                ('path_to_file', models.CharField(max_length=255)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_registration.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.IntegerField()),
                ('application_status', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cv_registration.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='applicant_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_appvoment', models.CharField(default='New', max_length=22)),
                ('program', models.CharField(max_length=50)),
                ('year_study', models.CharField(max_length=50)),
                ('recommendation', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('applicant_additional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cv_registration.university')),
                ('university_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cv_registration.university_agent')),
            ],
        ),
        migrations.CreateModel(
            name='accademic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=50)),
                ('year_started', models.DateField()),
                ('year_finished', models.DateField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_registration.applicant')),
            ],
        ),
    ]
