# Generated by Django 2.2.11 on 2020-03-19 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_student',
            name='applicant_additional',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicant_student',
            name='university_appvoment',
            field=models.CharField(choices=[('Approved', 'Approved'), ('DisApproved', 'DisApproved'), ('Pending', 'Pending')], default='Pending', max_length=14),
        ),
    ]
