# Generated by Django 2.2.11 on 2020-03-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_registration', '0003_applicant_non_university_appvoment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='non_university_appvoment',
        ),
        migrations.AddField(
            model_name='applicant',
            name='application_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('DisApproved', 'DisApproved'), ('Pending', 'Pending'), ('Submitted', 'Submitted')], default='Pending', max_length=14),
        ),
        migrations.AlterField(
            model_name='applicant_student',
            name='university_appvoment',
            field=models.CharField(choices=[('Approved', 'Approved'), ('DisApproved', 'DisApproved'), ('Pending', 'Pending'), ('not_submitted', 'not_submitted')], default='not_submitted', max_length=14),
        ),
    ]
