# Generated by Django 2.2.11 on 2020-03-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_registration', '0004_auto_20200321_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant_student',
            name='student_registration_no',
            field=models.CharField(default='L201529080113', max_length=50),
            preserve_default=False,
        ),
    ]
