# Generated by Django 2.2.11 on 2020-03-25 07:50

import cv_registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_registration', '0005_applicant_student_student_registration_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='user_image',
            field=models.ImageField(null=True, upload_to=cv_registration.models.user_directory_path, verbose_name='user_image'),
        ),
        migrations.AddField(
            model_name='university_agent',
            name='user_image',
            field=models.ImageField(null=True, upload_to=cv_registration.models.user_directory_path, verbose_name='user_image'),
        ),
    ]
