# Generated by Django 2.2.11 on 2020-03-25 13:04

import cv_registration.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cv_registration', '0006_auto_20200325_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='user_image',
            field=imagekit.models.fields.ProcessedImageField(default='11.jpg', null=True, upload_to=cv_registration.models.user_directory_path),
        ),
    ]
