# Generated by Django 2.2.11 on 2020-04-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_registration', '0007_auto_20200325_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='attachment_type',
            field=models.CharField(choices=[('other', 'Other'), ('motivation', 'Motivation'), ('certificates', 'Certificates'), ('reference_letter', 'reference_letter'), ('university_transcript', 'university_transcript')], default='other', max_length=14),
        ),
    ]
