# Generated by Django 2.2.11 on 2020-04-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_registration', '0009_attachment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='attachment_name',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment_type',
            field=models.CharField(choices=[('CV', 'cv'), ('Research Proposal', 'motivation_statement'), ('NIDA', 'NIDA'), ('Reference Letter', 'nomination_letter'), ('Reference Letter', 'Project_references'), ('Reference Letter', 'reference_letter'), ('Research contributions', 'research_contributions'), ('Research Proposal', 'research_proposal'), ('University Transcript', 'university_transcript'), ('Other', 'other')], default='Other', max_length=14),
        ),
    ]
