# Generated by Django 2.2.11 on 2020-04-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_registration', '0010_auto_20200415_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment_type',
            field=models.CharField(choices=[('CV', 'CV'), ('Research Proposal', 'motivation_statement'), ('NIDA', 'NIDA'), ('Reference Letter', 'nomination_letter'), ('Reference Letter', 'Project_references'), ('Reference Letter', 'Reference Letter'), ('Research contributions', 'Research Contributions'), ('Research Proposal', 'research_proposal'), ('University Transcript', 'university_transcript'), ('Other', 'other')], default='Other', max_length=14),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
