# Generated by Django 2.2.11 on 2020-04-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_registration', '0014_auto_20200415_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment_type',
            field=models.CharField(choices=[('CV', 'CV'), ('Motivation statement', 'Motivation Statement'), ('NIDA', 'NIDA'), ('Nomination letter', 'nomination_letter'), ('Project references', 'Project References'), ('Reference Letter', 'Reference Letter'), ('Research contributions', 'Research Contributions'), ('Research Proposal', 'research_proposal'), ('University Transcript', 'university_transcript'), ('Other', 'Other')], default='Other', max_length=14),
        ),
    ]
